# --- KEYBINDINGS ---
$mainMod = SUPER

# Essentials
bind = $mainMod, Q, exec, kitty              # Terminal
bind = $mainMod, C, killactive,              # Close window
bind = $mainMod, M, exit,                    # Exit Hyprland
bind = $mainMod, E, exec, dolphin            # File Manager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, rofi -show run     # Launcher
bind = $mainMod, P, pseudo,                  # dwindle
bind = $mainMod, J, togglesplit,             # dwindle
bind = $mainMod, W, exec, /home/skeken/.local/bin/Themes.sh

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
# ... (add up to 9 as needed)

# Move active window to a workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2

# Bind the function keys
bind = ,XF86MonBrightnessUp, exec, brightnessctl set 10%+
bind = ,XF86MonBrightnessDown, exec, brightnessctl set 10%-
bind = ,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = ,XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

# Scroll through existing workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
